// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41vFv0CSkuY97Grh9w8sHGWMOGL48bH8',
    appId: '1:992651454748:web:b0fb6b1caf854dab39f2d9',
    messagingSenderId: '992651454748',
    projectId: 'movies-app-4c38a',
    authDomain: 'movies-app-4c38a.firebaseapp.com',
    storageBucket: 'movies-app-4c38a.appspot.com',
    measurementId: 'G-B7FS9TP87G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCfyKWgSA3_CHik9YAKHpRcBzQ_ejaxPI',
    appId: '1:992651454748:android:43f8a6bb6a0f2cb839f2d9',
    messagingSenderId: '992651454748',
    projectId: 'movies-app-4c38a',
    storageBucket: 'movies-app-4c38a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-WxFitCmx07ZyPa3Kj95az4hqXhiPrI',
    appId: '1:992651454748:ios:2615f598b87e7afa39f2d9',
    messagingSenderId: '992651454748',
    projectId: 'movies-app-4c38a',
    storageBucket: 'movies-app-4c38a.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa-WxFitCmx07ZyPa3Kj95az4hqXhiPrI',
    appId: '1:992651454748:ios:f50b4da19dce611b39f2d9',
    messagingSenderId: '992651454748',
    projectId: 'movies-app-4c38a',
    storageBucket: 'movies-app-4c38a.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
